tl detection without project_to_image_plane (zoom in) and a classifier
alex-n-braun/carla.hal pull request #9
Opened 2017-09-17 14:06 UTC by YCSU

The __/traffic_waypoint__ topic now publishes the __index of the waypoint__ at which the car should stop. It publishes __-1__ when there is no traffic light in __red__ nearby, and publish the index for stopping when there is a traffic light in red near the car (now it is set to within 70 waypoints)

Since the classifier is not integrated yet, the state of the traffic light is obtained through __/vehicle/traffic_lights__.

2017-09-18 07:18 UTC, bmbigbang commented
ok this might need some trial and error to get right. why have u removed variable assignments to the subscribers?
+        rospy.Subscriber('/current_pose', PoseStamped, self.pose_cb)
+        rospy.Subscriber('/base_waypoints', Lane, self.waypoints_cb)

I see a lot people trying to do things that are not really necessary. lets not do this... as the commits are quite bulky at the moment so hard to read  through them

2017-09-18 08:42 UTC, YCSU commented
In the current situation, the variable assignments seem to be redundant since we use callback function to do what we need. With that said, I am not an expert in ROS. Is there any particular reason for the variable assignments?

2017-09-18 19:38 UTC, alex-n-braun commented
Hi Yu-Cheng,

I think a file called traffic_light_config.py is missing. 

Cheers,
Alex

2017-09-18 19:41 UTC, alex-n-braun requested changes
traffic_light_config.py is missing.

2017-09-18 19:41 UTC, alex-n-braun commented on ros/src/tl_detector/tl_detector.py
> +from traffic_light_config import config
this file seems to be missing.

2017-09-18 20:09 UTC, alex-n-braun commented on ros/src/tl_detector/tl_detector.py
> +        rospy.Subscriber('/camera/image_raw', Image, self.image_cb)
why /camera/image_raw, and not /image_color?

2017-09-19 01:55 UTC, YCSU commented
You are right! I checked the newest code from the Udacity repo. It looks like some part of my code comes from the older version. I will update it and upload it again tonight. Thanks!

2017-09-19 19:22 UTC, merged